<script type="text/javascript" src="plugins/jquery/jquery.js"></script>
<script type="text/javascript" src="plugins/popperjs/popper.js"></script>
<script type="text/javascript" src="plugins/bootstrap/js/bootstrap.js"></script>
<script type="text/javascript" src="plugins/fontawesome/js/all.js"></script>
<script type="text/javascript" src="plugins/datatables/datatables.js"></script>
<script type="text/javascript" src="plugins/sweetalert2/dist/sweetalert2.all.js"></script>
<script type="text/javascript" src="plugins/accountingjs/accountingjs.js"></script>
<script type="text/javascript" src="plugins/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="plugins/mathjs/math.js"></script>
<script type="text/javascript" src="custom/custom.js"></script>